# Learning Julia

This is me, thinking out loud, after/while watching a few Julia videos.

Julia looks a lot like Python. In fact, there might be a competition somewhere about who can write the longest program executable in both languages. Nah, a few colons and details might give it away though.

Before we get going, we need to install some stuff. Not a lot of fun, but we have to do it sooner or later. Funnily enough, there is a package for installing packages. Luckily, this comes pre-installed so we can just load it using the `using` keyword. Very similar to Python's `import`, but a different word because... cool.

In [1]:
using Pkg

So far so good. We'll get back to what these packages are, so far it's just some fairly random stuff I picked up in the videos.

In [2]:
Pkg.add("Plots")
Pkg.add("DataFrames")
Pkg.add("CSV")
Pkg.add("Statistics")
Pkg.add("Pipe")

   Updating registry at `/opt/julia/registries/General`


   Updating git-repo `https://github.com/JuliaRegistries/General.git`


    Fetching: [=============>                           ]  30.1 %

    Fetching: [=========================>

Fetching: [========================================>]  100.0 %

  Resolving package versions...
   Updating `/opt/julia/environments/v1.4/Project.toml`
 [no changes]
   Updating `/opt/julia/environments/v1.4/Manifest.toml`
 [no changes]
  Resolving package versions...
   Updating `/opt/julia/environments/v1.4/Project.toml`
 [no changes]
   Updating `/opt/julia/environments/v1.4/Manifest.toml`
 [no changes]
  Resolving package versions...
   Updating `/opt/julia/environments/v1.4/Project.toml`
 [no changes]
   Updating `/opt/julia/environments/v1.4/Manifest.toml`
 [no changes]
  Resolving package versions...
   Updating `/opt/julia/environments/v1.4/Project.toml`
 [no changes]
   Updating `/opt/julia/environments/v1.4/Manifest.toml`
 [no changes]
  Resolving package versions...
   Updating `/opt/julia/environments/v1.4/Project.toml`
 [no changes]
   Updating `/opt/julia/environments/v1.4/Manifest.toml`
 [no changes]


In [3]:
using Plots, DataFrames, CSV, Statistics, Pipe

Before we get going, lets do some warm-up exercises.

In [4]:
a = 42

42

In [5]:
a*a

1764

In [6]:
a^2

1764

In [7]:
b = "Hello world"

"Hello world"

In [8]:
b + b

MethodError: MethodError: no method matching +(::String, ::String)
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:529

In [9]:
concat(b, b)

UndefVarError: UndefVarError: concat not defined

In [10]:
concatenate(b, b)

UndefVarError: UndefVarError: concatenate not defined

Not as cool as Python, it seems.

As usual, StackOverflow has the answer. It's like the LEGO of tutorials. Why isn't that a thing yet? A tutorial simply as a lists of stackoverflow posts.

https://stackoverflow.com/questions/27827249/julia-concatenate-string-and-integer

In [11]:
string(b, b)

"Hello worldHello world"

By the way, this reminds me: f-strings go home, Julia is like PHP with the added benefit of not being PHP. Remember we defined that `a=42` variable way back when?

In [12]:
print("The answer is $a")

The answer is 42

One last thing: do some looping etc.

In [13]:
for a in 1:10
    print(a, "\n")
end

1
2
3
4
5
6
7
8
9
10


So like python but with `end` and not colon, and range definitions are stolen from R (which is stolen from S which is... whatevz).


Also, `str` is too short, but `string` lets you convert to... string!

In [14]:
string(1)

"1"

These oneliner function definitions are so cute I have completely forgotten how to write a more elaborate function.

In [15]:
hello(world) = println("Hello $world")

hello (generic function with 1 method)

In [16]:
hello("it's nice to meet you")

Hello it's nice to meet you


I think this is how:

In [17]:
function whatsup(world)
    println("Wussup $world")
end

whatsup (generic function with 1 method)

In [18]:
whatsup("y'all")

Wussup y'all


Lastly, we know these languages love maths, and matrices are built in like in R:

In [19]:
m = rand(3, 3)

3×3 Array{Float64,2}:
 0.968277  0.237871  0.263883
 0.256783  0.53111   0.986637
 0.951378  0.909077  0.364488

In [20]:
m*m

3×3 Array{Float64,2}:
 1.24969  0.596551  0.586386
 1.32368  1.24009   0.951391
 1.5014   1.04047   1.28083

In [21]:
m'*m

3×3 Array{Float64,2}:
 1.90862   1.23158   0.855629
 1.23158   1.16508   0.918131
 0.855629  0.918131  1.17594

The transpose (using `'`) is pretty funny. Actually, Julia is also in love with unicode, and can do a lot of strange stuff:

In [22]:
for a ∈ 1:3
    println(a)
end

1
2
3


In [23]:
😎 = "coolio"

"coolio"

In [24]:
print(😎)

coolio

The ∈ sign appears when you type `\in`, so basically brush up on your latex and you are once again the cool kid on the block.

But enough now, we want dataframes and more than just stdout and stdin.

We have a small file named `Batch_4154922_batch_results.csv` which is the output of an MTurk job, queued up for this.

In [25]:
df = CSV.read("Batch_4154922_batch_results.csv")

┌ Warning: `CSV.read(input; kw...)` is deprecated in favor of `using DataFrames; CSV.read(input, DataFrame; kw...)
│   caller = read(::String) at CSV.jl:40
└ @ CSV /opt/julia/packages/CSV/MKemC/src/CSV.jl:40


thread = 1 warning: only found 29 / 31 columns around data row: 2. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 3. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 4. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 5. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 6. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 7. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 8. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 9. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 10. Filling remaining columns with `missing`
thread = 1 warning: only fo

thread = 1 warning: only found 29 / 31 columns around data row: 97. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 98. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 99. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 100. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 101. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 102. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 103. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 104. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 105. Filling remaining columns with `missing`
thread = 1 wa

thread = 1 warning: only found 29 / 31 columns around data row: 191. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 192. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 193. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 194. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 195. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 196. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 197. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 198. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 199. Filling remaining columns with `missing`
thread = 1

thread = 1 warning: only found 29 / 31 columns around data row: 285. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 286. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 287. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 288. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 289. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 290. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 291. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 292. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 293. Filling remaining columns with `missing`
thread = 1

thread = 1 warning: only found 29 / 31 columns around data row: 379. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 380. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 381. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 382. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 383. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 384. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 385. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 386. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 387. Filling remaining columns with `missing`
thread = 1

thread = 1 warning: only found 29 / 31 columns around data row: 473. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 474. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 475. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 476. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 477. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 478. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 479. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 480. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 481. Filling remaining columns with `missing`
thread = 1

thread = 1 warning: only found 29 / 31 columns around data row: 567. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 568. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 569. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 570. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 571. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 572. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 573. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 574. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 575. Filling remaining columns with `missing`
thread = 1

thread = 1 warning: only found 29 / 31 columns around data row: 661. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 662. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 663. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 664. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 665. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 666. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 667. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 668. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 669. Filling remaining columns with `missing`
thread = 1

thread = 1 warning: only found 29 / 31 columns around data row: 755. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 756. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 757. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 758. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 759. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 760. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 761. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 762. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 763. Filling remaining columns with `missing`
thread = 1

thread = 1 warning: only found 29 / 31 columns around data row: 849. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 850. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 851. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 852. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 853. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 854. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 855. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 856. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 857. Filling remaining columns with `missing`
thread = 1

thread = 1 warning: only found 29 / 31 columns around data row: 943. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 944. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 945. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 946. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 947. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 948. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 949. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 950. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 951. Filling remaining columns with `missing`
thread = 1

thread = 1 warning: only found 29 / 31 columns around data row: 1036. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1037. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1038. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1039. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1040. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1041. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1042. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1043. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1044. Filling remaining columns with `missing`
t

thread = 1 warning: only found 29 / 31 columns around data row: 1129. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1130. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1131. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1132. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1133. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1134. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1135. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1136. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1137. Filling remaining columns with `missing`
t

thread = 1 warning: only found 29 / 31 columns around data row: 1222. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1223. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1224. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1225. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1226. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1227. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1228. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1229. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1230. Filling remaining columns with `missing`
t

thread = 1 warning: only found 29 / 31 columns around data row: 1315. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1316. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1317. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1318. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1319. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1320. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1321. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1322. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1323. Filling remaining columns with `missing`
t

thread = 1 warning: only found 29 / 31 columns around data row: 1408. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1409. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1410. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1411. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1412. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1413. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1414. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1415. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1416. Filling remaining columns with `missing`
t

thread = 1 warning: only found 29 / 31 columns around data row: 1501. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1502. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1503. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1504. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1505. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1506. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1507. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1508. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1509. Filling remaining columns with `missing`
t

thread = 1 warning: only found 29 / 31 columns around data row: 1594. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1595. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1596. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1597. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1598. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1599. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1600. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1601. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1602. Filling remaining columns with `missing`
t

thread = 1 warning: only found 29 / 31 columns around data row: 1687. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1688. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1689. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1690. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1691. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1692. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1693. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1694. Filling remaining columns with `missing`
thread = 1 warning: only found 29 / 31 columns around data row: 1695. Filling remaining columns with `missing`
t

1760×31 DataFrame. Omitted printing of 29 columns
│ Row  │ HITId                          │ HITTypeId                      │
│      │ String                         │ String                         │
├──────┼────────────────────────────────┼────────────────────────────────┤
│ 1    │ 301KG0KX9BKTP2L7XD15P8Y69GP2HK │ 36ENCJ709J8WC06EPA4JOHGF537KEH │
│ 2    │ 301KG0KX9BKTP2L7XD15P8Y69GP2HK │ 36ENCJ709J8WC06EPA4JOHGF537KEH │
│ 3    │ 301KG0KX9BKTP2L7XD15P8Y69GP2HK │ 36ENCJ709J8WC06EPA4JOHGF537KEH │
│ 4    │ 301KG0KX9BKTP2L7XD15P8Y69GP2HK │ 36ENCJ709J8WC06EPA4JOHGF537KEH │
│ 5    │ 301KG0KX9BKTP2L7XD15P8Y69GP2HK │ 36ENCJ709J8WC06EPA4JOHGF537KEH │
│ 6    │ 301KG0KX9BKTP2L7XD15P8Y69GP2HK │ 36ENCJ709J8WC06EPA4JOHGF537KEH │
│ 7    │ 301KG0KX9BKTP2L7XD15P8Y69GP2HK │ 36ENCJ709J8WC06EPA4JOHGF537KEH │
│ 8    │ 301KG0KX9BKTP2L7XD15P8Y69GP2HK │ 36ENCJ709J8WC06EPA4JOHGF537KEH │
│ 9    │ 301KG0KX9BKTP2L7XD15P8Y69GP2HK │ 36ENCJ709J8WC06EPA4JOHGF537KEH │
│ 10   │ 301KG0KX9BKTP2L7XD15P8Y69GP2HK │ 36ENCJ709J8WC06EPA4JOHGF537KEH │
⋮
│ 1750 │ 3ZXV7Q5FJANM9OM3ZG2BY0VF5SPCF5 │ 36ENCJ709J8WC06EPA4JOHGF537KEH │
│ 1751 │ 3ZZAYRN1I5QX1I17K5GRA44XLFGOTM │ 36ENCJ709J8WC06EPA4JOHGF537KEH │
│ 1752 │ 3ZZAYRN1I5QX1I17K5GRA44XLFGOTM │ 36ENCJ709J8WC06EPA4JOHGF537KEH │
│ 1753 │ 3ZZAYRN1I5QX1I17K5GRA44XLFGOTM │ 36ENCJ709J8WC06EPA4JOHGF537KEH │
│ 1754 │ 3ZZAYRN1I5QX1I17K5GRA44XLFGOTM │ 36ENCJ709J8WC06EPA4JOHGF537KEH │
│ 1755 │ 3ZZAYRN1I5QX1I17K5GRA44XLFGOTM │ 36ENCJ709J8WC06EPA4JOHGF537KEH │
│ 1756 │ 3ZZAYRN1I5QX1I17K5GRA44XLFGOTM │ 36ENCJ709J8WC06EPA4JOHGF537KEH │
│ 1757 │ 3ZZAYRN1I5QX1I17K5GRA44XLFGOTM │ 36ENCJ709J8WC06EPA4JOHGF537KEH │
│ 1758 │ 3ZZAYRN1I5QX1I17K5GRA44XLFGOTM │ 36ENCJ709J8WC06EPA4JOHGF537KEH │
│ 1759 │ 3ZZAYRN1I5QX1I17K5GRA44XLFGOTM │ 36ENCJ709J8WC06EPA4JOHGF537KEH │
│ 1760 │ 3ZZAYRN1I5QX1I17K5GRA44XLFGOTM │ 36ENCJ709J8WC06EPA4JOHGF537KEH │

Some warnings there, but let's worry about those later. So far, it looks like we have a dataframe. There is a `head` function but it told me it was deprecated and that I should use `first` instead.

In [26]:
first(df, 5)

5×31 DataFrame. Omitted printing of 29 columns
│ Row │ HITId                          │ HITTypeId                      │
│     │ String                         │ String                         │
├─────┼────────────────────────────────┼────────────────────────────────┤
│ 1   │ 301KG0KX9BKTP2L7XD15P8Y69GP2HK │ 36ENCJ709J8WC06EPA4JOHGF537KEH │
│ 2   │ 301KG0KX9BKTP2L7XD15P8Y69GP2HK │ 36ENCJ709J8WC06EPA4JOHGF537KEH │
│ 3   │ 301KG0KX9BKTP2L7XD15P8Y69GP2HK │ 36ENCJ709J8WC06EPA4JOHGF537KEH │
│ 4   │ 301KG0KX9BKTP2L7XD15P8Y69GP2HK │ 36ENCJ709J8WC06EPA4JOHGF537KEH │
│ 5   │ 301KG0KX9BKTP2L7XD15P8Y69GP2HK │ 36ENCJ709J8WC06EPA4JOHGF537KEH │

Somehow this uses only the first three columns and there doesn't seem to be a way to get more columns.

Also, I learned you could do this:

In [27]:
?first

search: first firstindex popfirst! pushfirst! uppercasefirst lowercasefirst



```
first(coll)
```

Get the first element of an iterable collection. Return the start point of an [`AbstractRange`](@ref) even if it is empty.

# Examples

```jldoctest
julia> first(2:2:10)
2

julia> first([1; 2; 3; 4])
1
```

---

```
first(s::AbstractString, n::Integer)
```

Get a string consisting of the first `n` characters of `s`.

```jldoctest
julia> first("∀ϵ≠0: ϵ²>0", 0)
""

julia> first("∀ϵ≠0: ϵ²>0", 1)
"∀"

julia> first("∀ϵ≠0: ϵ²>0", 3)
"∀ϵ≠"
```

---

```
first(q::Deque)
```

Returns the first element of the deque `q`.

---

```
first(D::CircularDeque)
```

Get the item at the front of the queue.

---

```
first(s::Stack)
```

Get the top item from the stack. Sometimes called peek.

---

```
first(h::BinaryHeap)
```

Returns the element at the top of the heap `h`.

---

```
first(h::BinaryMinMaxHeap)
```

Get the first (minimum) of the heap.

---

```
first(sc)
```

Argument `sc` is a SortedDict, SortedMultiDict or SortedSet. This function returns the first item (a `k=>v` pair for SortedDict and SortedMultiDict or a key for SortedSet) according to the sorted order in the container. Thus, `first(sc)` is equivalent to `deref((sc,startof(sc)))`. It is an error to call this function on an empty container. Time: O(log *n*)

---

```
first(sc)
```

Argument `sc` is a SortedDict, SortedMultiDict or SortedSet. This function returns the first item (a `k=>v` pair for SortedDict and SortedMultiDict or a key for SortedSet) according to the sorted order in the container. Thus, `first(sc)` is equivalent to `deref((sc,startof(sc)))`. It is an error to call this function on an empty container. Time: O(log *n*)

---

```
first(sc)
```

Argument `sc` is a SortedDict, SortedMultiDict or SortedSet. This function returns the first item (a `k=>v` pair for SortedDict and SortedMultiDict or a key for SortedSet) according to the sorted order in the container. Thus, `first(sc)` is equivalent to `deref((sc,startof(sc)))`. It is an error to call this function on an empty container. Time: O(log *n*)

---

```
first(cb::CircularBuffer)
```

Get the first element of CircularBuffer.

---

```
first(df::AbstractDataFrame)
```

Get the first row of `df` as a `DataFrameRow`.

---

```
first(df::AbstractDataFrame, n::Integer)
```

Get a data frame with the `n` first rows of `df`.


Column names are pretty straight forward, but we still don't have a lot of info on what this really is.

In [28]:
names(df)

31-element Array{String,1}:
 "HITId"
 "HITTypeId"
 "Title"
 "Description"
 "Keywords"
 "Reward"
 "CreationTime"
 "MaxAssignments"
 "RequesterAnnotation"
 "AssignmentDurationInSeconds"
 "AutoApprovalDelayInSeconds"
 "Expiration"
 "NumberOfSimilarHITs"
 ⋮
 "AutoApprovalTime"
 "ApprovalTime"
 "RejectionTime"
 "RequesterFeedback"
 "WorkTimeInSeconds"
 "LifetimeApprovalRate"
 "Last30DaysApprovalRate"
 "Last7DaysApprovalRate"
 "Input.document_url"
 "Answer.category.label"
 "Approve"
 "Reject"

In [29]:
summary(df)

"1760×31 DataFrame"

OK that wasn't what I wanted, maybe it was `describe`.

In [30]:
describe(df)

31×8 DataFrame. Omitted printing of 6 columns
│ Row │ variable                    │ mean    │
│     │ Symbol                      │ Union…  │
├─────┼─────────────────────────────┼─────────┤
│ 1   │ HITId                       │         │
│ 2   │ HITTypeId                   │         │
│ 3   │ Title                       │         │
│ 4   │ Description                 │         │
│ 5   │ Keywords                    │         │
│ 6   │ Reward                      │         │
│ 7   │ CreationTime                │         │
│ 8   │ MaxAssignments              │ 10.0    │
│ 9   │ RequesterAnnotation         │         │
│ 10  │ AssignmentDurationInSeconds │ 120.0   │
⋮
│ 21  │ ApprovalTime                │         │
│ 22  │ RejectionTime               │         │
│ 23  │ RequesterFeedback           │         │
│ 24  │ WorkTimeInSeconds           │ 28.6028 │
│ 25  │ LifetimeApprovalRate        │         │
│ 26  │ Last30DaysApprovalRate      │         │
│ 27  │ Last7DaysApprovalRate       │         │
│ 28  │ Input.document_url          │         │
│ 29  │ Answer.category.label       │         │
│ 30  │ Approve                     │         │
│ 31  │ Reject                      │         │

Better. We're still nowhere near where we need to be, but at least we now have a feeling for what is categorical and what is numeric, which is good enough. I want to group and summarize, the de-facto "hello, world" of data. And I heard rumor that there is a pipe operator that is pretty sweet.

In [31]:
@pipe df |> 
    groupby(_, :LifetimeApprovalRate) |> 
    combine(_, :WorkTimeInSeconds => mean, :LifetimeApprovalRate => length)

6×3 DataFrame. Omitted printing of 1 columns
│ Row │ LifetimeApprovalRate │ WorkTimeInSeconds_mean │
│     │ String               │ Float64                │
├─────┼──────────────────────┼────────────────────────┤
│ 1   │ 100% (5/5)           │ 9.232                  │
│ 2   │ 100% (1/1)           │ 28.3122                │
│ 3   │ 100% (2/2)           │ 30.8978                │
│ 4   │ 100% (3/3)           │ 31.6377                │
│ 5   │ 100% (4/4)           │ 23.9587                │
│ 6   │ 0% (0/0)             │ 33.7305                │

Works. Two surprises: 
- the `@pipe` decorator (I'm assuming that's what it is) is less elegant than R
- having to do a count using `length` is... somehow both unnatural and very logical. I hope I'm not doing it right.

That being said, we have now performed the "Hello, World" of data. Let's get down to more business.

Next things do do:
- I want to regex the shit out of some of these variables.
- Not a lot of fan of the column names after aggregation

It seems substring works almost like in Python, except leaving it blank on one side of the colon gives weird results. I guess that's a basic function of how stuff/arrays work in Julia.

In [32]:
"Hello"[:4]

'l': ASCII/Unicode U+006C (category Ll: Letter, lowercase)

In [33]:
"Hello"[1:4]

"Hell"

In [34]:
length("Hello")

5

I have no idea what is going on with negative indexes. It's definetely not like python, and why it doesn't give an error on `"Hello"[2:-2]` is beyond me.

In [35]:
print("Hello"[-2])

BoundsError: BoundsError: attempt to access String
  at index [-2]

In [36]:
print("Hello"[-2:2])

BoundsError: BoundsError: attempt to access String
  at index [-2:2]

In [37]:
print("Hello"[2:-2])

It seems there are some other functions that can help.

In [38]:
print(firstindex("Hello"), ", ", lastindex("Hello"))

1, 5

In [39]:
SubString("Hello", 2, 4)

"ell"

In [40]:
"Hello"[end-1:end]

"lo"

So... this is fairly unusual: There is a special value, `end`, that seems to denote end of string, and that can be used as a helper when subsetting. And there is a `SubString` function that takes takes start-position and end-position (my least favorite arguments). The documentation suggest substring might be a good friend once you venture outside of ASCII territory, because the subsetting is a little too simple-minded. I know it's a detour, but I want to try it:

In [41]:
a = "🐰, how are you?"

println(a[1:5])

🐰,


OK, so the first four characters are a rabbit, which makes sense. Last try:

In [42]:
b = " Hi ÆØÅ"

println(b[1:6])

StringIndexError: StringIndexError(" Hi ÆØÅ", 6)

In [43]:
println(SubString(b, 1, 6))

StringIndexError: StringIndexError(" Hi ÆØÅ", 6)

In [44]:
println(SubString(b, 1, 5))

 Hi Æ


That's the spirit! Everything crashes if you slice an overlong byte. I'm sure there's a way to get around it.

So, to the regex stuff. There doesn't seem to be any separate regex library like python's `re`, and regex-patterns can be defined suspiciously simply:

In [45]:
ptn = r"^[0-9]{1,3}\%"

r"^[0-9]{1,3}\%"

In [46]:
m = match(ptn, "100% (2/2)")

RegexMatch("100%")

In [47]:
m[1]

BoundsError: BoundsError: attempt to access 0-element Array{Union{Nothing, SubString{String}},1} at index [1]

In [48]:
names(m)

MethodError: MethodError: no method matching names(::RegexMatch)
Closest candidates are:
  names(!Matched::DataFrames.Index) at /opt/julia/packages/DataFrames/cdZCk/src/other/index.jl:34
  names(!Matched::Module; all, imported) at reflection.jl:98
  names(!Matched::DataFrames.SubIndex) at /opt/julia/packages/DataFrames/cdZCk/src/other/index.jl:421
  ...

This looked so simple, but how to get our wonderful match out of the regex object. Subsetting did not work, and trying to be fancy interrogating the object with `names` similar to what I love to do in Python with `dir`, threw an error.

Anyways, maybe we can do something else, using, say, `matchall`.

In [49]:
m2 = matchall(ptn, "100% (2/2)")

UndefVarError: UndefVarError: matchall not defined

OK, the function found on stackoverflow isn't defined, maybe because the post was from 2014. New languages are a bitch. It seems the `RegexMatch` object has methods like `match` and `captures` and `offset`.

In [50]:
m.match

"100%"

In [51]:
m.captures

0-element Array{Union{Nothing, SubString{String}},1}

In [52]:
m.offset

1

OK, whatevs, match is what I want for now. But seriously, if matchall isn't a function, what do you use when you want to capture more than one result? There can be two things in a string.

So we want to assign a new variable using an existing variable. This takes two things (in addition to the function): Accessing the existing variable, and assigning the new one.

In [54]:
first(df.AssignmentDurationInSeconds)

120

In [55]:
df.newvariable = "abcd"

┌ Warning: `setproperty!(df::DataFrame, col_ind::Symbol, v)` is deprecated, use `df[!, col_ind] .= v` instead.
│   caller = top-level scope at In[55]:1
└ @ Core In[55]:1


"abcd"

Hmmm... interesting, some new syntax here. The `.=` is peculiar. Let's try.

In [58]:
df[!, "newvar"] .= "abc"

1760-element Array{String,1}:
 "abc"
 "abc"
 "abc"
 "abc"
 "abc"
 "abc"
 "abc"
 "abc"
 "abc"
 "abc"
 "abc"
 "abc"
 "abc"
 ⋮
 "abc"
 "abc"
 "abc"
 "abc"
 "abc"
 "abc"
 "abc"
 "abc"
 "abc"
 "abc"
 "abc"
 "abc"

In [59]:
names(df)

33-element Array{String,1}:
 "HITId"
 "HITTypeId"
 "Title"
 "Description"
 "Keywords"
 "Reward"
 "CreationTime"
 "MaxAssignments"
 "RequesterAnnotation"
 "AssignmentDurationInSeconds"
 "AutoApprovalDelayInSeconds"
 "Expiration"
 "NumberOfSimilarHITs"
 ⋮
 "RejectionTime"
 "RequesterFeedback"
 "WorkTimeInSeconds"
 "LifetimeApprovalRate"
 "Last30DaysApprovalRate"
 "Last7DaysApprovalRate"
 "Input.document_url"
 "Answer.category.label"
 "Approve"
 "Reject"
 "newvariable"
 "newvar"

So far so good. Let's try putting it together.

In [71]:
[eltype(col) for col = eachcol(df)]

33-element Array{Type,1}:
 String
 String
 String
 String
 String
 String
 String
 Int64
 String
 Int64
 Int64
 String
 Missing
 ⋮
 Missing
 Missing
 Int64
 String
 String
 String
 String
 String
 Missing
 Missing
 String
 String

In [60]:
df[!, "pctapproval"] .= match.(r"^[0-9]{1,3}\%", df[!, "LifetimeApprovalRate"]).match

ErrorException: type Array has no field match

So, probably got some broadcasting issue going on here, thought that was what the dot after the function was for, but whatever. Googling how to assign variable in julia should return something, I presume.

OK lets take a step back:

In [62]:
Pkg.add("DataFramesMeta")

  Resolving package versions...
  Installed DataFramesMeta ─ v0.5.1
   Updating `/opt/julia/environments/v1.4/Project.toml`
  [1313f7d8] + DataFramesMeta v0.5.1
   Updating `/opt/julia/environments/v1.4/Manifest.toml`
  [1313f7d8] + DataFramesMeta v0.5.1


In [63]:
using DataFramesMeta

┌ Info: Precompiling DataFramesMeta [1313f7d8-7da2-5740-9ea0-a2ca25f37964]
└ @ Base loading.jl:1260


In [70]:
df2 = @linq df |>
    @transform(worktimeinminutes = :LifetimeApprovalRate ./ 60)

MethodError: MethodError: no method matching transform(::Nothing; worktimeinminutes=var"#3#4"())
Closest candidates are:
  transform(!Matched::AbstractDataFrame; kwargs...) at /opt/julia/packages/DataFramesMeta/c67UK/src/DataFramesMeta.jl:377
  transform(!Matched::GroupedDataFrame; kwargs...) at /opt/julia/packages/DataFramesMeta/c67UK/src/DataFramesMeta.jl:385

It's fun to copy-paste internet code because internet code is the best code. Somehow internet code gave errors though. But don't worry, we found more internet code! This time functional, which is much promising.

In [118]:
df.somethingsomething = map( x -> match(r"^[0-9]{1,3}\%", x).match, df[!,:LifetimeApprovalRate] )

1760-element PooledArrays.PooledArray{SubString{String},UInt32,1,Array{UInt32,1}}:
 "100%"
 "100%"
 "100%"
 "100%"
 "100%"
 "100%"
 "100%"
 "100%"
 "100%"
 "100%"
 "100%"
 "100%"
 "100%"
 ⋮
 "0%"
 "100%"
 "100%"
 "100%"
 "100%"
 "100%"
 "100%"
 "0%"
 "100%"
 "0%"
 "100%"
 "100%"

OK apparantly that works now when I didn't try to somehow pass the regex in as y, so yeab basically a lambda function because it works. But I'll own up to it, I did have a few other trys.

In [83]:
df.newstuff = match.(r"^[0-9]{1,3}\%", df[!, :LifetimeApprovalRate]).match

ErrorException: type Array has no field match

In [91]:
[thing.match for thing in match.(r"^[0-9]{1,3}\%", ["4%blah", "5%blah"])]

2-element Array{SubString{String},1}:
 "4%"
 "5%"

OK, we could probably use a list comprehension, to apply the match property on the match function, but better to just make our own short function

In [108]:
function getrx(txt)
    match(r"^[0-9]{1,3}\%", txt).match
end

df.anotherthing = getrx.(df[!, :LifetimeApprovalRate])

1760-element Array{SubString{String},1}:
 "100%"
 "100%"
 "100%"
 "100%"
 "100%"
 "100%"
 "100%"
 "100%"
 "100%"
 "100%"
 "100%"
 "100%"
 "100%"
 ⋮
 "0%"
 "100%"
 "100%"
 "100%"
 "100%"
 "100%"
 "100%"
 "0%"
 "100%"
 "0%"
 "100%"
 "100%"

In [115]:
df.anotherthing[1:3]

3-element Array{SubString{String},1}:
 "100%"
 "100%"
 "100%"

Really wanted to use `first` or `head`, but apparantly that doesn't work on singe columns. Luckily, I totally forgot that a column is an array and I could just have subsetted it like normal humans.

At least you didn't have to sit and watch me. Let's just say I deleted some cells.

So OK we have created a new variable that's not just something trivial like `a+1` or something. Let's try the aggregation again.

In [119]:
@pipe df |>
    groupby(_, :anotherthing) |>
    combine(_, :WorkTimeInSeconds => mean, :LifetimeApprovalRate => length)

2×3 DataFrame
│ Row │ anotherthing │ WorkTimeInSeconds_mean │ LifetimeApprovalRate_length │
│     │ SubString…   │ Float64                │ Int64                       │
├─────┼──────────────┼────────────────────────┼─────────────────────────────┤
│ 1   │ 100%         │ 26.5624                │ 1259                        │
│ 2   │ 0%           │ 33.7305                │ 501                         │